import assert from 'node:assert/strict';
import test from 'node:test';
import {currentWorkspaceMovements} from '../replay/currentWorkspaceMovements.ts';
import {workspaceMotionOwnership} from '../replay/workspaceMotionOwnership.ts';
import {prepareReplay} from '../replay/prepareReplay.ts';
import {buildWorkspaceLifetimeContours} from '../replay/workspaceLifetimeContours.ts';
const atom=(id,label='N')=>({id,label,children:[]});
const fork=(id,...children)=>({id,label:'P',children});
function view(root){const nodes=new Map(),parents=new Map();const visit=(n,p)=>{nodes.set(n.id,n);if(p)parents.set(n.id,p);n.children.forEach(c=>visit(c,n.id));};visit(root);return{nodes,ids:()=>nodes.keys(),has:id=>nodes.has(id),parent:id=>parents.get(id),children:id=>nodes.get(id)?.children.map(c=>c.id)??[],contains:(root,id)=>{for(let p=id;p;p=parents.get(p))if(p===root)return true;return false;},members:function*(id){const queue=[id];while(queue.length){const id=queue.shift();yield id;queue.push(...nodes.get(id).children.map(c=>c.id));}}};}
const step=(options={})=>({replayKind:'relation',replayRelationIdentity:{stageIndex:1,relationIndex:0},replayRelationLinks:[{authoredRelationKey:'1:0',renderFamily:'authored-anchor-link',movementTransition:true,priorSourceNodeId:'source',witnessNodeId:'lower',targetNodeId:'landing',...options}]});
function pair(){const host=fork('host',atom('word'));return{before:view(fork('p',host,atom('source'),atom('other'))),current:view(fork('p',fork('wrapper',atom('landing'),{...structuredClone(host),label:'changed'}),atom('lower'),atom('other')))};}
const key=(v,id)=>JSON.stringify([id,...v.children(id).map(c=>key(v,c))]);
function ownership(before,current,op){return workspaceMotionOwnership({step:op,before,current,sameMaterial:id=>JSON.stringify(before.nodes.get(id))===JSON.stringify(current.nodes.get(id)),sameTopology:id=>before.has(id)&&current.has(id)&&key(before,id)===key(current,id)});}
test('proved covert transition owns exact endpoints and material-changing receiving host',()=>{const {before,current}=pair(),op=step(),result=ownership(before,current,op);assert.equal(currentWorkspaceMovements(op,before,current).length,1);assert.deepEqual([...result.owned].sort(),['host','landing','lower','source','word']);assert.deepEqual(result.stationary,['other']);});
for(const options of [{movementTransition:false,renderFamily:'trajectory'},{movementTransition:undefined},{authoredRelationKey:'0:0'},{priorSourceNodeId:'missing'},{witnessNodeId:'landing'},{targetNodeId:'missing'}])test(`unproved/stale endpoints cannot acquire ownership ${JSON.stringify(options)}`,()=>{const {before,current}=pair();assert.equal(currentWorkspaceMovements(step(options),before,current).length,0);assert.equal(ownership(before,current,step(options)).owned.size,0);});
test('persisted proof cannot authorize a structural or unrelated relation frame',()=>{const {before,current}=pair();assert.equal(currentWorkspaceMovements({...step(),replayKind:'micro'},before,current).length,0);assert.equal(currentWorkspaceMovements({...step(),replayRelationIdentity:{stageIndex:1,relationIndex:1}},before,current).length,0);});
test('receiving-host topology change cannot release its retained descendant',()=>{const {before,current}=pair();current.nodes.get('host').children.push(atom('added'));const rebuilt=view(current.nodes.get('p')),result=ownership(before,rebuilt,step());assert(!result.owned.has('host'));assert(!result.owned.has('word'));assert(result.stationary.includes('word'));});
const ids=n=>[n.id,...n.children.flatMap(ids)];
test('material-changing receiver retains its child contour under its exact new wrapper',()=>{const {before,current}=pair();const a=before.nodes.get('p'),b=current.nodes.get('p'),steps=[{replayCanvasData:a,replayVisibleNodeIds:ids(a),replayKind:'micro'},{...step(),replayCanvasData:b,replayVisibleNodeIds:ids(b)}];const initial=buildWorkspaceLifetimeContours(steps),preferred=new Map(initial.flatMap(f=>[...f.nodes.values()].map(s=>[s.incarnation,new Map(s.members)])));const frames=buildWorkspaceLifetimeContours(steps,undefined,undefined,undefined,undefined,undefined,{inheritCurrentSlots:true,preferred});assert.deepEqual(frames[0].nodes.get('host').members.get('word'),frames[1].nodes.get('host').members.get('word'));assert.equal(frames[1].nodes.get('p').members.get('wrapper').y,frames[1].nodes.get('p').members.get('lower').y);});
function covertRecord(){const lower={id:'lower',label:'DP',lineageId:'object',children:[{id:'n',label:'N',word:'book'}]};const host={id:'host',label:'TP',children:[{id:'v',label:'V',word:'read'},lower]};const high={id:'high',label:'DP',lineageId:'object',silent:true,children:[{id:'nh',label:'N',word:'book'}]};return{sentence:'read book',includePlayback:true,derivationStages:[{statement:'one',stageRecord:'one',relations:[],workspaceForest:[structuredClone(host)]},{statement:'two',stageRecord:'two',relations:[{relation:'covert object Internal Merge',anchors:{higherOccurrence:'high',lowerOccurrence:'lower',scopeHost:'host'},priorAnchors:{source:'lower'},values:{pronunciation:'lower copy'}}],workspaceForest:[{id:'wrapper',label:'TP',children:[high,host]}]}]};}
test('compiler exports covert proof without changing its identity presentation',()=>{const record=covertRecord(),copy=structuredClone(record),prepared=prepareReplay(record),op=prepared.playbackSteps.find(s=>s.replayKind==='relation');assert(op);const link=op.replayRelationLinks.find(l=>l.authoredRelationKey==='1:0');assert.equal(link.movementTransition,true);assert.equal(link.renderFamily,'authored-anchor-link');assert.equal(link.priorSourceNodeId,'lower');assert.equal(link.witnessNodeId,'lower');assert.equal(link.targetNodeId,'high');assert.deepEqual(record,copy);});
test('unproved authored identity never gains structural-transition metadata',()=>{const record=covertRecord();delete record.derivationStages[0].workspaceForest[0].children[1].lineageId;const prepared=prepareReplay(record);assert(!prepared.playbackSteps.some(s=>s.replayRelationLinks?.some(l=>l.movementTransition===true)));});
test('a retained lower occurrence follows its rigid host through an owned new wrapper',()=>{const source=atom('source'),still=atom('still'),host=fork('host',source,still),side=atom('side');const a=fork('p',side,host),b=fork('p',side,fork('wrapper',atom('landing'),host));const steps=[{replayCanvasData:a,replayVisibleNodeIds:ids(a),replayKind:'micro'},{...step({witnessNodeId:'source'}),replayCanvasData:b,replayVisibleNodeIds:ids(b)}];const initial=buildWorkspaceLifetimeContours(steps),preferred=new Map(initial.flatMap(f=>[...f.nodes.values()].map(s=>[s.incarnation,new Map(s.members)])));const frames=buildWorkspaceLifetimeContours(steps,undefined,undefined,undefined,undefined,undefined,{inheritCurrentSlots:true,preferred});assert.equal(frames[0].nodes.get('host'),frames[1].nodes.get('host'));assert.equal(frames[1].nodes.get('p').members.get('side').y,frames[1].nodes.get('p').members.get('wrapper').y);for(const bad of [{movementTransition:false},{authoredRelationKey:'0:0'}]){const invalid=structuredClone(steps);Object.assign(invalid[1].replayRelationLinks[0],bad);assert.throws(()=>buildWorkspaceLifetimeContours(invalid,undefined,undefined,undefined,undefined,undefined,{inheritCurrentSlots:true,preferred}),/Incompatible current ranks/);}});
