import { tokenizeSentenceSurfaceOrder } from './surfaceTokens.js';
import { NOTES_RAW_JSON_ONLY_INSTRUCTION } from './systemInstruction.js';

export const buildProGrowthFirstContentsPrompt = (
  sentence,
  framework = 'xbar'
) => {
  const tokens = tokenizeSentenceSurfaceOrder(sentence);
  const tokenText = tokens.join(' | ');
  const tokenIndexText = tokens.map((token, index) => `${index}:${token}`).join(' | ');
  return (
    `Analyze the sentence: "${sentence}" and return a complete syntactic analysis using ` +
    `${framework === 'xbar' ? 'X-Bar Theory' : 'The Minimalist Program (Bare Phrase Structure)'} in Babel's Pro Growth-first JSON format. ` +
    `Return raw JSON only, with no markdown, no code fences, no labels, and no prose before or after the JSON object. ` +
    `Return the complete structural analysis in one pass. ` +
    `Return growthFrames plus any typed ledgers that are genuinely supported by the same derivation. Do not return noteBindings on this first pass; Babel will request model-authored noteBindings separately from the frozen committed analysis after the syntax is fixed. ` +
    `You may also include optional typed ledgers such as chains, researchTrace, caseAssignments, argumentStructure, phaseLog, morphologyRealization, featureLedger, selectionLedger, bindingLedger, clausalDependencies, agreementLedger, predicateClassLedger, probeLedger, nullElementLedger, diagnosticLedger, parameterLedger, informationStructureLedger, operatorScopeLedger, voiceValencyLedger, linearizationLedger, localityLedger, and predicationLedger when they are genuinely supported by the same derivation. ` +
    `If the analysis turns on a real structural decision, include concise researchTrace entries that record the competing options, the chosen commitment, and the derivational support. researchTrace is an explicit typed decision journal, not raw scratchpad or private monologue. ` +
    `On the Pro route, treat caseAssignments, argumentStructure, and selectionLedger as core outputs for any argument-bearing clause rather than optional garnish: return them explicitly whenever the derivation contains overt or covert arguments, thematic relations, or complement/specifier selection. For optional ledgers that truly have nothing to record, omit the field rather than returning an empty array with no information. ` +
    `growthFrames are the only structural source of truth, and Babel will derive Canopy plus any flat step log from them. ` +
    `noteBindings are the only Notes source of truth, and Babel will request them in a second model-authored pass over the frozen analysis before rendering the final Notes paragraph. ` +
    `Use a strict public support graph: growthFrames encode the derivation, public ledgers encode typed facts from that same derivation, and noteBindings only explain those same authored facts. StepIds/nodeIds are enough for plain structural descriptions, but they are not enough for typed claims about null elements, predicate class, voice/valency, agreement/probe behavior, parameters, information structure, operator scope, linearization, or locality. Any note that mentions one of those typed domains must cite supportIds for the matching authored ledger entries. If you cannot author the matching ledger entry, narrow the note to the directly visible Growth fact instead of mentioning the typed domain. ` +
    `On the Pro route, if Notes explicitly mention case, theta roles, selector/selectee relations, or raising/control/ECM, return matching caseAssignments, argumentStructure, selectionLedger, or clausalDependencies instead of leaving those commitments only in prose. ` +
    `Use these exact overt input tokens as your pronounced terminals: ${tokenText}. ` +
    `For overt terminal leaves, include tokenIndex values tied to that token list: ${tokenIndexText}. ` +
    `Do not split, rewrite, or duplicate those overt tokens. ` +
    `The latest decisive Growth frame must be a single rooted committed structure whose overt terminals, read left-to-right, spell exactly: ${tokenText}. ` +
    `Do not stop at a pre-convergence frame: continue the derivation until every overt movement and head movement needed for the actual sentence has been encoded and the latest decisive frame itself already realizes the surface order. ` +
    `${framework === 'xbar'
      ? `Use InflP (not TP) for finite clausal structure, use CP as the root projection for finite clause-level parses unless the input is clearly a non-clausal fragment, and keep X-bar branching strictly binary. If an adjunct is added, realize it through recursive bar-level shells rather than ternary branching. `
      : `Use Minimalist/Bare Phrase Structure labels consistently and keep the final committed clause root appropriate to the analysis. `}` +
    `${framework === 'xbar'
      ? `For finite V2 clauses or topicalized finite clauses, keep the clause-initial fronted XP in Spec,CP and keep C' binary as C' -> C + InflP; do not treat a fronted clause-initial topicalized XP as if it were merely Spec,InflP. `
      : ''}` +
    `Never use positional placeholders such as Spec,CP, Spec,InflP, or Comp as node labels. Encode actual phrase categories (DP, CP, InflP, VP, etc.), and represent specifier/complement status only by where those category nodes sit in the tree. ` +
    `Every syntax node inside growthFrames must use the canonical nested shape {"id":"...","label":"...","children":[...]}. Do not use alternate field names like nodeId, and never place a child object directly inside a node object without the key "children". If a node has one child, children must still be an array containing that one child. If workspaceForest has one root, it must still be an array containing that root. ` +
    `Return each frame's full workspace forest directly in "workspaceForest" as ordinary structured JSON, not as a stringified blob. The workspaceForest value should be the complete array of syntax roots for that frame. If a frame sets reusePreviousWorkspace:true and the structure truly does not change, you may omit workspaceForest on that frame. "workspaceForestJson" is accepted only for legacy compatibility; prefer structured "workspaceForest" whenever possible. If you include optional ledgers such as chains, caseAssignments, argumentStructure, selectionLedger, bindingLedger, or clausalDependencies, return each ledger entry as an ordinary JSON object inside the array rather than as a compact JSON string. featureChecking and noteBindings should also remain ordinary structured JSON objects. ` +
    `If movement occurs, make it explicit and keep noteBindings and growthFrames consistent with the same one movement story. ` +
    `For every move-like Growth frame (Move, InternalMerge, HeadMove, A-Move, AbarMove), include a "movement" object with operation, sourceNodeId, targetNodeId, and note, using node ids that exist in that frame's workspaceForest. Never point movement at a bare label placeholder like Spec or C' unless that node carries an explicit id in the same frame. ` +
    `Every move-like Growth frame is invalid unless it also includes that movement object. Do not label a frame A-Move, AbarMove, HeadMove, InternalMerge, or Move and then omit the movement payload. ` +
    `If one dependency moves through multiple copies or phase edges, reuse the same chainId across those Growth frames so the chain remains unified rather than split into isolated hops. ` +
    `Do not collapse distinct movement dependencies into one frame. If the sentence contains both head movement and phrasal movement, encode them as separate move-like frames with separate chain notes. ` +
    `A one-frame derivation is acceptable only when the analysis has no movement, no lower trace/copy, no PRO/control/raising/ECM dependency, and no cross-clausal dependency that needs to be made explicit. Otherwise, return at least one earlier structural frame before the final committed frame. ` +
    `For phrasal movement, the lower source must be the full overt moved phrase before movement, not just one head inside it, and after movement the lower site should be a trace/copy only. ` +
    `Once a phrase has moved, the pronounced landing copy must remain overt at its committed landing site. Do not make both the lower source and the higher landing copy traces or null copies. ` +
    `If a phrasal copy survives after movement, keep the full phrase shell and make the lower copy an explicit indexed trace/copy rather than leaving blank shells or a bare unindexed t. Use canonical lower-copy notation such as t_1, t_2, t_subj, or t_obj in the returned Growth JSON; Babel will render subscripts. ` +
    `When a thematic subject ultimately surfaces high, Growth should still show its lower thematic merge site before later movement rather than treating the final landing site as the only overt source state. ` +
    `If a thematic argument later surfaces in a higher licensing position, include at least one earlier structural frame where that argument is still present in its lower merge position before the relevant movement or licensing step. ` +
    `If the sentence involves a clause-linking dependency such as raising, control, or ECM, encode that dependency explicitly in clausalDependencies and keep Growth faithful to the same analysis rather than flattening it into one final-state-only frame. ` +
    `Do not encode control as ordinary A-movement: keep the controller in its clause, keep the silent controlled subject distinct, and record the dependency in clausalDependencies rather than inventing a movement chain for it. ` +
    `If one predicate selects an overt finite or non-finite clause as its complement, record that embedding relation in clausalDependencies as well as in selectionLedger; do not leave clause embedding only implicit in the tree or only in prose. ` +
    `The latest decisive Growth frame must realize the entire input sentence, not only an embedded clause or another partial substructure. Do not stop after a lower clause, VP shell, or any incomplete workspace: finish with one committed frame whose overt terminals match the full sentence in order. ` +
    `For control, raising, or ECM on the Pro route, clausalDependencies must name the relation participants explicitly with controllerLabel/dependentLabel or the appropriate raised/dependent labels, and should include predicateLabel and clauseLabel whenever those can be read from the committed derivation. ` +
    `Do not leave hidden movement implicit. If the latest decisive frame contains any trace/copy node or if any note mentions movement, chain formation, raising, or lowering, then Growth must also contain the corresponding explicit move-like frame(s) and chainId-linked note binding(s). ` +
    `If one chain moves through more than one landing site, preserve each intermediate copy as a distinct node with its own node id so the derivation can draw each hop separately rather than collapsing all arrows onto one landing site. ` +
    `If a chain crosses more than one landing site or edge, encode each hop as its own explicit movement frame with the same chainId. Do not describe intermediate landing sites in noteBindings unless growthFrames actually contain those distinct intermediate movement frames. ` +
    `If the pronounced sentence begins with a fronted wh/topic XP, a derivation that encodes only head movement is incomplete: include an explicit AbarMove frame whose target is that left-peripheral landing site and whose source is the lower overt/base position. ` +
    `If a finite interrogative, V2 clause, or inversion pattern surfaces an overt auxiliary or functional head before the subject, encode the corresponding HeadMove explicitly and place that overt landed head in C in the latest decisive frame rather than leaving it only in Infl. ` +
    `For head movement, the lower source must be a lower head or head-copy, not a whole phrase containing that head. ` +
    `Do not relocate a lexical verb, adjective, or preposition into Infl or C unless the derivation explicitly encodes that head movement. If no overt head movement is intended, keep the lexical item in its base head and realize finiteness or clause typing through the appropriate functional head instead of replacing the lower lexical site with a bare trace. ` +
    `For head movement landing sites, represent one overt landed head and one lower trace/copy, not malformed shells like C -> [Infl hat] [C ∅]. ` +
    `growthFrames must form a dense frame-by-frame derivational timeline. Use a separate frame for each meaningful lexical selection, projection, external merge, feature-licensing/case/EPP event, movement event, and spellout event. ` +
    `Do not compress several derivational operations into one frame or collapse lexical selection, projection, and merge into one step. ` +
    `Return separate Growth frames for separate derivational operations whenever you can. Use "microOperations" only as a last-resort disclosure device when one returned frame genuinely summarizes more than one local action because you could not safely emit finer-grained structural states; do not rely on microOperations as the normal strategy. ` +
    `A Growth analysis is invalid if its only returned structure is a fragment such as a lone DP, NP, VP shell, or embedded subclause rather than the full clause being analyzed. Even the simplest finite clause must continue until the derivation reaches a full committed clause, not stop after building one phrase. ` +
    `Prefer enough structural Growth frames to keep lower merge, licensing, intermediate landing sites, and final landing sites distinct whenever those are distinct commitments in the derivation. Long-distance, raising/control, or successive-cyclic dependencies should therefore normally surface as richer multi-frame timelines rather than as one compressed jump. ` +
    `Prefer canonical operation names such as LexicalSelect, Project, ExternalMerge, Agree, A-Move, AbarMove, HeadMove, SpellOutDomain, and SpellOut. Do not use the generic operation name "Other" when one of those specific operations fits the step. ` +
    `Each Growth frame must include stepId and operation. Include workspaceForest unless reusePreviousWorkspace:true is enough because the structural workspace is unchanged. ` +
    `Include affectedNodeIds, chainId, featureChecking, thetaRole, spelloutDomain, or note only when they express an explicit commitment in that frame. If you include frame.note or frame.recipe, it must name the actual structural change in that frame; never use stock boilerplate such as "Initial logic and parameters are validated", "Standard processing applied", or "Final transformation". ` +
    `When a step changes licensing or feature state without changing overt tree shape, you may set reusePreviousWorkspace: true instead of repeating an identical workspaceForest, but you must still record that step explicitly. ` +
    `Do not leave case, EPP, agreement, or wh-licensing only in the noteBindings. When those commitments are part of the analysis, encode them inside the relevant Growth frames through featureChecking and, when straightforward, on the relevant node via case, assigner, caseEvidence, or caseOvert. ` +
    `If a note binding mentions Nominative, Accusative, Dative, Genitive, Ergative, Absolutive, or another morphological/syntactic case value, return matching caseAssignments and/or matching featureChecking on the relevant derivational step; do not leave case values only in prose. On the Pro route, explicit case claims require caseAssignments unless the case value is already fully and unambiguously represented in featureChecking on the relevant derivational step. When a note mentions case, cite the relevant caseAssignments directly with caseAssignmentIds rather than relying only on generic supportIds. ` +
    `If you return caseAssignments, each assignment must identify the assignee explicitly with nodeId or assigneeLabel, not just the case value and assigner. If you return argumentStructure, each entry must identify the referent and predicate explicitly rather than leaving them implicit. Do not emit partial theta-role entries like { role: "Agent", predicate: "eat" } with no referent. If the argument is not explicit, omit that entry rather than returning a half-specified one. ` +
    `If the analysis explicitly claims Nominative, Accusative, interrogative C-licensing, or another feature-driven dependency, make that visible in Growth rather than only in prose. ` +
    `On the Pro route, if noteBindings explicitly mention Agent, Theme, Patient, Experiencer, Goal, Proposition, or another theta-role, return matching argumentStructure entries rather than leaving those thematic commitments only in prose. Each such entry must name both the predicate and the argument referent explicitly in readable linguistic terms rather than leaving one side implicit. If noteBindings or the architecture note describe a DP as an external argument, an object as an internal argument, or a clause/head as selecting a DP, CP, VP, or another complement, return matching argumentStructure and selectionLedger entries rather than leaving those commitments only in prose. Explicit theta-role claims require argumentStructure on the Pro route rather than leaving theta-role information only in prose. ` +
    `Treat ledgers as typed summaries of facts that are already explicit in growthFrames, not as an independent second analysis. Do not use a ledger to introduce a syntactic fact that is not already encoded in the derivation. When you include a public ledger entry, anchor it back into the derivation with stepIds and/or nodeIds whenever the relevant support is identifiable in Growth. If a noteBinding makes a structured claim, that same claim must already be supported by growthFrames and, when you include a dedicated ledger for it, by the matching ledger entry as well. If the Notes say that a head selects two complements or a complement plus a specifier, selectionLedger must name that selector and those selected dependents explicitly rather than returning [] or a vague placeholder. Do not emit selector-only entries with no selectedCategory or selectedLabel. Use readable phrase/head labels, not internal placeholders like VP1, InflP_mat, node ids, or other implementation-only names. ` +
    `Do not let noteBindings or ledgers outrun the derivation. If a note would mention case, theta roles, selector/selectee relations, agreement, control, binding, locality, predication, or linearization but the matching fact is not encoded in growthFrames, simplify the note rather than asserting unsupported detail. ` +
    `Movement does not cancel ordinary predicate-argument bookkeeping. If an XP moves, still return the same caseAssignments, argumentStructure, and selectionLedger entries that would hold of its base-generated role and selector relation; do not drop those ledgers merely because the sentence is a wh-question, topicalization, or another fronting configuration. ` +
    `For raising, control, or ECM analyses, clausalDependencies is required rather than optional on the Pro route. Use subtype labels when appropriate, such as subject-control, object-control, raising-to-subject, raising-to-object, or ECM. For explicit theta-role claims, argumentStructure is required rather than optional on the Pro route. ` +
    `If noteBindings or the architecture note commit to control, raising, or ECM, clausalDependencies must include the matching type and the most specific compatible subtype rather than leaving subtype as a generic placeholder like "control" or "raising". ` +
    `If the architecture note says that a predicate selects an embedded clause, return a matching clausalDependencies entry for that clause embedding rather than leaving the embedding relation only in prose. Use a type such as finite-complement when the embedded clause is an ordinary finite complement and no more specific raising/control/ECM subtype is intended. ` +
    `If the analysis explicitly commits to head selection, binding domains, Principle A/B/C-style dependencies, or raising/control/ECM relations, prefer to record those in selectionLedger, bindingLedger, or clausalDependencies rather than stuffing every detail into noteBindings. On the Pro route, any explicit Principle A/B/C or reflexive/anaphor note should come with bindingLedger rather than leaving binding information only in prose. ` +
    `Return noteBindings as an ordered array of model-authored note sentences that explain the derivation encoded in growthFrames. Each note binding sentence should use the field "text". Every noteBinding object is invalid unless it carries at least one anchor field: chainId, stepIds, nodeIds, supportIds, or researchTraceIds. Every note binding must anchor itself back into the derivation with stepIds and/or nodeIds whenever the supporting step or nodes are identifiable, and chain notes should include both chainId and the relevant stepIds/nodeIds. When a note is directly supported by particular ledger entries, attach that support explicitly with supportIds and the matching typed ids. supportIds should cite the stable ids of the relevant ledger entries. ChainId and stepIds alone are not sufficient when a chain note also mentions typed facts such as case, theta roles, linearization, locality, agreement, diagnostics, voice, predicate class, information structure, or operator scope: in that situation, cite the matching typed ledger entries as well. Notes must not introduce a new public syntactic fact on their own: every structural claim in a note must already be grounded in growthFrames, and any claim that uses a dedicated ledger type should cite the matching ledger entry with supportIds. ` +
    `Keep movement narration inside chain notes. Architecture and licensing notes should describe final architecture, selection, and licensing only; do not use them to narrate a movement path or to make predicate-class/voice/null-element claims unless the matching typed ledger support is also returned and cited. ` +
    `Do not leave architecture, licensing, or closure notes structurally unanchored. If an architecture/licensing/closure note mentions headedness, word order, surface adjacency, extraposition, inversion, or another typed derivational fact, attach the relevant supportIds and any matching typed ids rather than returning a free-floating summary sentence. ` +
    `If you return researchTrace, you may include at most one or two noteBindings that summarize the decisive reasoning in compact scientific prose, but those notes must cite the relevant researchTrace decision ids with researchTraceIds and/or supportIds. Do not dump raw scratchpad text into Notes. ` +
    `If a note mentions case, theta roles, selector/selectee relations, binding, agreement, predicate class, probe behavior, null elements, diagnostics, parameters, information structure, operator scope, voice/valency, linearization, locality, or predication, return the matching typed ledger and cite it from that note with the corresponding typed ids and/or supportIds. If a note mentions surface order, word order, inversion, V2, fronting, head-initial/head-final, or another linearization fact, linearizationLedger is required. If a note mentions locality, a phase edge, the left periphery as a landing requirement, successive-cyclic movement, minimality, or another boundary-sensitive movement fact, localityLedger is required. If you cannot return the matching ledger support, simplify or omit the note instead of asserting unsupported detail. Typed-domain words in Notes are commitments, not decoration: do not use words such as passive, focus, topic, scope, unaccusative, raising predicate, control predicate, Ergative, or Nominative unless the matching public ledger support is present and cited. Case notes should cite caseAssignmentIds explicitly, not only broad supportIds. ` +
    `Return exactly one public analysis for the sentence. Do not return analyses arrays, alternative trees, or ambiguity notes. ` +
    `The first binding must have kind "architecture" and explain the committed clause architecture, selection, and headedness rather than narrating movement details. ` +
    `The architecture binding must describe the final committed architecture, not a stale pre-move configuration. Do not describe an overt auxiliary or moved phrase as if it still only occupies its lower source position once the committed Growth derivation lands it higher. ` +
    `In noteBindings and optional ledgers, use readable linguistic labels rather than internal placeholders such as V1, V2, VP1, CP_emb, InflP_mat, or raw node ids. Prefer phrases like lower V shell, higher V shell, embedded CP, matrix InflP, or the overt phrase itself. ` +
    `A note binding must not mention any movement type unless the same derivation explicitly encodes the matching move-like frame and chain. Do not describe head movement, A-movement, A-bar movement, raising, lowering, or shell-internal displacement in prose unless growthFrames encode that dependency explicitly. If a shell analysis is used without an explicit head-movement frame, describe the shell architecture and selection facts only rather than claiming that the head moved. ` +
    `If the analysis encodes movement, include public "chains" with one entry for each encoded movement chain. Do not omit "chains" merely because growthFrames already imply the dependency. ` +
    `Include one binding of kind "chain" for each encoded movement chain (each A-chain, each A-bar chain, and each head-movement chain), and attach each such binding to the relevant chain via chainId. ` +
    `Do not omit subject A-movement chains merely because they are local licensing steps. If an embedded or matrix subject A-moves to Spec,InflP or another overt landing site, that subject A-chain must still receive its own chain binding. ` +
    `In multi-clausal derivations, include separate chain bindings for embedded subject A-movement, matrix subject A-movement, head movement, and A-bar movement whenever those chains are encoded. ` +
    `If a chain undergoes more than one move, the corresponding chain note must describe the full path from base position through any intermediate landing to the final landing rather than stopping at the first hop. ` +
    `Each chain note must describe the committed landing site or landing sites encoded in growthFrames. Do not say that a moved head or phrase merely occupies its lower source if Growth already lands it higher. If head movement lands an auxiliary in C, the chain note must say that it moves or lands in C rather than leaving it only in Infl. ` +
    `Do not hide movement facts inside architecture or licensing notes when a corresponding chain note should exist; movement paths belong in chain notes. ` +
    `When case, EPP, theta-role introduction, control, raising, ECM, or other licensing commitments are explicit and not already fully covered by the architecture/chain sentences, you may include additional bindings of kind "licensing". ` +
    `If an embedded subject is PRO in a control analysis, do not describe PRO as moving or as originating in a derived landing site such as Spec,InflP. Describe it simply as the silent embedded subject/base position and encode the control relation in clausalDependencies. ` +
    `If clausalDependencies encodes control, raising, or ECM, include at least one non-chain note binding that explicitly states that dependency and names the relevant controller/dependent or raised argument, rather than leaving the dependency only in backend bookkeeping. ` +
    `You may include a final binding of kind "closure" only when it adds a specific framework-relevant structural observation beyond the architecture, chain, and licensing notes already given. Prefer omitting closure entirely unless it contributes a new concrete payoff not already stated. ` +
    `Do not use generic wrap-up boilerplate such as "the derivation converges", "the overt word order is successfully derived", "the surface constituent order is derived", "the analysis successfully captures", or "this demonstrates how" followed by generic filler. If a closure sentence adds no concrete structural content, omit it. ` +
    `Prefer direct structural closure wording over self-evaluative phrasing: say what the derivation establishes, not that it "successfully captures" or "demonstrates" something in general. ` +
    `A good closure sentence should name a real structural payoff already encoded in Growth, such as locality, a case/theta asymmetry, or a committed dependency contrast. If you cannot name a concrete payoff like that, do not return a closure binding. Phrase closure sentences as direct structural claims, not as self-referential sentences beginning with "This derivation" or "The analysis". Do not use closure merely to repeat movement, head-movement, or architecture facts that are already explicit in earlier note bindings. ` +
    `Every note binding must be a complete sentence, compact but elegant, with explicit structural wording rather than generic fallback prose. The Notes should sound like concise research notes, not robotic diagnostics. ` +
    `You may include brief interpretive or theory-flavored framing only when it is genuinely supported by the derivation and does not contradict any commitment encoded in growthFrames. ` +
    `Every chain note must use chainId. Every chain note in noteBindings must include "chainId" and at least one structural anchor such as "stepIds" or "nodeIds", and every other note binding must still describe only structure and dependencies that are encoded in growthFrames. ` +
    `If a noteBinding makes a typed claim about case, theta-role/argument structure, selection, binding, clausal dependency, agreement/probe, predicate class, null elements, diagnostics, parameters, information structure, operator scope, voice/valency, linearization, locality, or predication, attach the matching typed ids on that noteBinding. Do not rely on generic supportIds alone for typed claims. ` +
    `If movement is encoded, public "chains" are required on the Pro route. Every chain note on the Pro route must include chainId plus at least one of stepIds or nodeIds. ` +
    `Before returning, compare noteBindings against the encoded move-like frames and make sure no encoded chain is omitted from the Notes. ` +
    `FINAL CHECK: return one coherent JSON answer only. growthFrames must be the authoritative derivation, and the latest decisive Growth frame must be sufficient for Babel to derive the final Canopy. Count your growthFrames before returning: fewer than 3 frames on the Pro route is incomplete. Also run a final note-support self-audit: if any note uses a typed theoretical label, confirm that the matching public ledger exists and is cited; otherwise simplify the note back down to the directly visible Growth fact. Favor structural clarity and explicit derivational truth over unnecessary bookkeeping.`
  );
};

export const buildLiteGrowthFirstContentsPrompt = (
  sentence,
  framework = 'xbar'
) => {
  const tokens = tokenizeSentenceSurfaceOrder(sentence);
  const tokenText = tokens.join(' | ');
  const tokenIndexText = tokens.map((token, index) => `${index}:${token}`).join(' | ');
  return (
    `Analyze the sentence: "${sentence}" and return a complete syntactic analysis using ` +
    `${framework === 'xbar' ? 'X-Bar Theory' : 'The Minimalist Program (Bare Phrase Structure)'} in Babel's Lite Growth-first JSON format. ` +
    `Return raw JSON only, with no markdown, no code fences, no labels, and no prose before or after the JSON object. ` +
    `Return the complete analysis in one pass. ` +
    `Return growthFrames and noteBindings. You may include lightweight optional ledgers such as caseAssignments, argumentStructure, clausalDependencies, agreementLedger, predicateClassLedger, probeLedger, nullElementLedger, diagnosticLedger, parameterLedger, informationStructureLedger, operatorScopeLedger, voiceValencyLedger, linearizationLedger, localityLedger, or predicationLedger when they are genuinely supported by the same derivation, but on the Lite route correctness of growthFrames and noteBindings matters more than optional bookkeeping richness. ` +
    `If the analysis turns on a real structural decision, you may include concise researchTrace entries that record the competing options, the chosen commitment, and the derivational support. researchTrace is an explicit typed decision journal, not raw scratchpad or private monologue. ` +
    `growthFrames are the only structural source of truth, and Babel will derive Canopy plus any flat replay log from them. ` +
    `noteBindings are the only Notes source of truth, and Babel will render the final Notes paragraph directly from them in order. ` +
    `Use a strict public support graph: growthFrames encode the derivation, public ledgers encode typed facts from that same derivation, and noteBindings only explain those same authored facts. StepIds/nodeIds are enough for plain structural descriptions, but they are not enough for typed claims about null elements, predicate class, voice/valency, agreement/probe behavior, parameters, information structure, operator scope, linearization, or locality. Any note that mentions one of those typed domains must cite supportIds for the matching authored ledger entries. If you cannot author the matching ledger entry, narrow the note to the directly visible Growth fact instead of mentioning the typed domain. ` +
    `Use these exact overt input tokens as your pronounced terminals: ${tokenText}. ` +
    `For overt terminal leaves, include tokenIndex values tied to that token list: ${tokenIndexText}. ` +
    `Do not split, rewrite, or duplicate those overt tokens. ` +
    `The latest decisive Growth frame must be a single rooted committed structure whose overt terminals, read left-to-right, spell exactly: ${tokenText}. ` +
    `Do not stop at a pre-convergence frame: continue the derivation until every overt movement and head movement needed for the actual sentence has been encoded and the latest decisive frame itself already realizes the surface order. ` +
    `${framework === 'xbar'
      ? `Use InflP (not TP) for finite clausal structure, use CP as the root projection for finite clause-level parses unless the input is clearly a non-clausal fragment, and keep X-bar branching binary. `
      : `Use Minimalist/Bare Phrase Structure labels consistently and keep the final committed clause root appropriate to the analysis. `}` +
    `${framework === 'xbar'
      ? `For finite V2 clauses or topicalized finite clauses, keep the clause-initial fronted XP in Spec,CP and keep C' binary as C' -> C + InflP; do not treat a fronted clause-initial topicalized XP as if it were merely Spec,InflP. `
      : ''}` +
    `Never use positional placeholders such as Spec,CP, Spec,InflP, or Comp as node labels. Encode actual phrase categories (DP, CP, InflP, VP, etc.), and represent specifier/complement status only by where those category nodes sit in the tree. ` +
    `Return each frame's full workspace forest directly in "workspaceForest" as ordinary structured JSON, not as a stringified blob. The workspaceForest value should be the complete array of syntax roots for that frame. If a frame sets reusePreviousWorkspace:true and the structure truly does not change, you may omit workspaceForest on that frame. "workspaceForestJson" is accepted only for legacy compatibility; prefer structured "workspaceForest" whenever possible. If you include optional ledgers such as chains, caseAssignments, argumentStructure, selectionLedger, bindingLedger, or clausalDependencies, return each ledger entry as an ordinary JSON object inside the array rather than as a compact JSON string. featureChecking and noteBindings should also remain ordinary structured JSON objects. ` +
    `If movement occurs, make it explicit and keep noteBindings and growthFrames consistent with the same one movement story. ` +
    `For each move-like Growth frame, include a movement object with operation, sourceNodeId, targetNodeId, and note, using node ids that exist in that frame's workspaceForest. Never point movement at a bare label placeholder like Spec or C' unless that node carries an explicit id in the same frame. ` +
    `Every move-like Growth frame is invalid unless it also includes that movement object. Do not label a frame A-Move, AbarMove, HeadMove, InternalMerge, or Move and then omit the movement payload. ` +
    `On the Lite route, Growth may be more compact than Pro, but it must still be derivational rather than tree-first. Include a separate frame whenever lexical selection, projection, merge, licensing, movement, or spellout changes the committed analysis in a meaningful way. If you must choose, prefer a shorter derivation that still explicitly encodes every real movement dependency over a richer but incomplete derivation. ` +
    `Return separate Growth frames for separate derivational operations whenever you can. Use "microOperations" only as a last-resort disclosure device when one Lite frame genuinely summarizes more than one local action and you cannot safely emit finer-grained structural states. ` +
    `Do not collapse distinct movement dependencies into one Lite frame. If the sentence contains both head movement and phrasal movement, encode them as separate move-like frames with separate chain notes, even if the overall Lite derivation stays shorter than Pro. ` +
    `A one-frame Lite derivation is acceptable only when the analysis has no movement, no lower trace/copy, no PRO/control/raising/ECM dependency, and no cross-clausal dependency that needs to be made explicit. Otherwise, return at least one earlier structural frame before the final committed frame. ` +
    `Every Growth frame is invalid unless it includes both frameId and operation. Do not omit operation on any frame. Use canonical operation names such as LexicalSelect, Project, ExternalMerge, Agree, A-Move, AbarMove, HeadMove, SpellOutDomain, or SpellOut, and do not use the generic operation name "Other" when one of those specific operations fits the step. ` +
    `If movement occurs, include at least one lower-overt frame before the movement and one post-move frame in which the lower site is an explicit trace/copy such as t_1, t_2, t_subj, or t_obj. Do not leave blank shells or a bare unindexed t. ` +
    `A Growth analysis is invalid if its only returned structure is a fragment such as a lone DP, NP, VP shell, or embedded subclause rather than the full clause being analyzed. Even a simple finite clause must continue until the derivation reaches a full committed clause, not stop after building one phrase. ` +
    `Once a phrase has moved, the pronounced landing copy must remain overt at its committed landing site. Do not make both the lower source and the higher landing copy traces or null copies. ` +
    `When a thematic subject surfaces high, Growth should still show its lower thematic merge site before later A-movement unless the subject is explicitly expletive or otherwise non-thematic. ` +
    `If a thematic argument later surfaces in a higher licensing position, include at least one earlier structural frame where that argument is still present in its lower merge position before the relevant movement or licensing step. ` +
    `If the sentence involves a clause-linking dependency such as raising, control, or ECM, encode that dependency explicitly in clausalDependencies and keep Growth faithful to the same analysis rather than flattening it into one final-state-only frame. ` +
    `The latest decisive Growth frame must realize the entire input sentence, not only an embedded clause or another partial substructure. Do not stop after a lower clause, VP shell, or any incomplete workspace: finish with one committed frame whose overt terminals match the full sentence in order. ` +
    `Do not encode control as ordinary A-movement: keep the controller in its clause, keep the silent controlled subject distinct, and record the dependency in clausalDependencies rather than inventing a movement chain for it. ` +
    `If one predicate selects an overt finite or non-finite clause as its complement, record that embedding relation in clausalDependencies as well as in selectionLedger; do not leave clause embedding only implicit in the tree or only in prose. ` +
    `If the architecture note says that a predicate selects an embedded clause, return a matching clausalDependencies entry for that clause embedding rather than leaving the embedding relation only in prose. Use a type such as finite-complement when the embedded clause is an ordinary finite complement and no more specific raising/control/ECM subtype is intended. ` +
    `Do not leave hidden movement implicit. If the latest decisive frame contains any trace/copy node or if any note mentions movement, chain formation, raising, or lowering, then Growth must also contain the corresponding explicit move-like frame(s) and chainId-linked note binding(s). ` +
    `If a chain crosses more than one landing site or edge, encode each hop as its own explicit movement frame with the same chainId. Do not describe intermediate landing sites in noteBindings unless growthFrames actually contain those distinct intermediate movement frames. ` +
    `If the pronounced sentence begins with a fronted wh/topic XP, a derivation that encodes only head movement is incomplete: include an explicit AbarMove frame whose target is that left-peripheral landing site and whose source is the lower overt/base position. ` +
    `If a finite interrogative, V2 clause, or inversion pattern surfaces an overt auxiliary or functional head before the subject, encode the corresponding HeadMove explicitly and place that overt landed head in C in the latest decisive frame rather than leaving it only in Infl. ` +
    `${framework === 'xbar'
      ? `Keep X-bar headedness explicit in the committed structure: finite CPs should branch through C' rather than collapsing directly into C plus InflP, and overtly expanded DPs/NPs should keep their headed bar-level shell rather than collapsing into a bare phrase with two daughters. `
      : ''}` +
    `Silent heads must be represented overtly as the null terminal "∅"; do not leave an empty head node with children: []. ` +
    `Traces and silent copies are not overt terminals: never assign tokenIndex to t_1, t_2, t_subj, t_obj, trace, or ∅. ` +
    `Do not realize the same overt word twice inside one committed frame. If a head has moved to Infl or C, the lower site must be a trace/copy/null, not the same overt word again. ` +
    `Do not relocate a lexical verb, adjective, or preposition into Infl or C unless the derivation explicitly encodes that head movement. If no overt head movement is intended, keep the lexical item in its base head and realize finiteness or clause typing through the appropriate functional head instead of replacing the lower lexical site with a bare trace. ` +
    `If the latest decisive frame still spells a different order from the input, do not return yet: add the missing move/head-move/spellout frame(s) until the committed frame itself matches the sentence. ` +
    `For head movement landing sites, represent one overt landed head and one lower trace/copy, not malformed shells like C -> [Infl hat] [C ∅]. ` +
    `Return noteBindings as an ordered array of model-authored note sentences that explain the derivation encoded in growthFrames. Each note binding sentence should use the field "text". Every noteBinding object is invalid unless it carries at least one anchor field: chainId, stepIds, nodeIds, supportIds, or researchTraceIds. Every note binding must anchor itself back into the derivation with stepIds and/or nodeIds whenever the supporting step or nodes are identifiable, and chain notes should include both chainId and the relevant stepIds/nodeIds. When a note is directly supported by particular ledger entries, attach that support explicitly with supportIds and the matching typed ids. supportIds should cite the stable ids of the relevant ledger entries. ChainId and stepIds alone are not sufficient when a chain note also mentions typed facts such as case, theta roles, linearization, locality, agreement, diagnostics, voice, predicate class, information structure, or operator scope: in that situation, cite the matching typed ledger entries as well. Notes must not introduce a new public syntactic fact on their own: every structural claim in a note must already be grounded in growthFrames, and any claim that uses a dedicated ledger type should cite the matching ledger entry with supportIds. ` +
    `Keep movement narration inside chain notes. Architecture and licensing notes should describe final architecture, selection, and licensing only; do not use them to narrate a movement path or to make predicate-class/voice/null-element claims unless the matching typed ledger support is also returned and cited. ` +
    `Do not leave architecture, licensing, or closure notes structurally unanchored. If an architecture/licensing/closure note mentions headedness, word order, surface adjacency, extraposition, inversion, or another typed derivational fact, attach the relevant supportIds and any matching typed ids rather than returning a free-floating summary sentence. ` +
    `If you return researchTrace, you may include at most one short noteBinding that summarizes the decisive reasoning in compact scientific prose, but that note must cite the relevant researchTrace decision ids with researchTraceIds and/or supportIds. Do not dump raw scratchpad text into Notes. ` +
    `If a note mentions case, theta roles, selector/selectee relations, binding, agreement, predicate class, probe behavior, null elements, diagnostics, parameters, information structure, operator scope, voice/valency, linearization, locality, or predication, return the matching typed ledger and cite it from that note with the corresponding typed ids and/or supportIds. If a note mentions surface order, word order, inversion, V2, fronting, head-initial/head-final, or another linearization fact, linearizationLedger is required. If a note mentions locality, a phase edge, the left periphery as a landing requirement, successive-cyclic movement, minimality, or another boundary-sensitive movement fact, localityLedger is required. If you cannot return the matching ledger support, simplify or omit the note instead of asserting unsupported detail. Typed-domain words in Notes are commitments, not decoration: do not use words such as passive, focus, topic, scope, unaccusative, raising predicate, control predicate, Ergative, or Nominative unless the matching public ledger support is present and cited. Case notes should cite caseAssignmentIds explicitly, not only broad supportIds. ` +
    `When you include a public ledger entry, anchor it back into the derivation with stepIds and/or nodeIds whenever the relevant support is identifiable in Growth. ` +
    `Return exactly one public analysis for the sentence. Do not return analyses arrays, alternative trees, or ambiguity notes. ` +
    `The first binding must have kind "architecture" and should describe clause architecture, selection, and headedness rather than narrating movement details. If movement is encoded, include one binding of kind "chain" for each encoded movement chain, and attach each such binding to the relevant chain via chainId. ` +
    `Do not omit subject A-movement chains merely because they are local licensing steps. If an embedded or matrix subject A-moves to Spec,InflP or another overt landing site, that subject A-chain must still receive its own chain binding. ` +
    `In multi-clausal derivations, include separate chain bindings for embedded subject A-movement, matrix subject A-movement, head movement, and A-bar movement whenever those chains are encoded. ` +
    `The architecture binding must describe the final committed architecture, not a stale pre-move configuration. Do not describe an overt auxiliary or moved phrase as if it still only occupies its lower source position once the committed Growth derivation lands it higher. ` +
    `In noteBindings and optional ledgers, use readable linguistic labels rather than internal placeholders such as V1, V2, VP1, CP_emb, InflP_mat, or raw node ids. Prefer phrases like lower V shell, higher V shell, embedded CP, matrix InflP, or the overt phrase itself. ` +
    `A note binding must not mention any movement type unless the same derivation explicitly encodes the matching move-like frame and chain. Do not describe head movement, A-movement, A-bar movement, raising, lowering, or shell-internal displacement in prose unless growthFrames encode that dependency explicitly. If a shell analysis is used without an explicit head-movement frame, describe the shell architecture and selection facts only rather than claiming that the head moved. ` +
    `If the analysis encodes movement, include public "chains" with one entry for each encoded movement chain. Do not omit "chains" merely because growthFrames already imply the dependency. ` +
    `Each chain note must describe the committed landing site or landing sites encoded in growthFrames. Do not say that a moved head or phrase merely occupies its lower source if Growth already lands it higher. If head movement lands an auxiliary in C, the chain note must say that it moves or lands in C rather than leaving it only in Infl. ` +
    `Do not hide movement facts inside architecture or licensing notes when a corresponding chain note should exist; movement paths belong in chain notes. ` +
    `When case, EPP, theta-role introduction, control, raising, ECM, or other licensing commitments are explicit and not already fully covered by the architecture/chain sentences, you may include additional bindings of kind "licensing". ` +
    `If an embedded subject is PRO in a control analysis, do not describe PRO as moving or as originating in a derived landing site such as Spec,InflP. Describe it simply as the silent embedded subject/base position and encode the control relation in clausalDependencies. ` +
    `If clausalDependencies encodes control, raising, or ECM, include at least one non-chain note binding that explicitly states that dependency and names the relevant controller/dependent or raised argument, rather than leaving the dependency only in backend bookkeeping. ` +
    `If noteBindings explicitly mention Agent, Theme, Patient, Experiencer, Goal, or another theta-role, try to return matching argumentStructure entries rather than leaving those thematic commitments only in prose. Each such entry should still name the predicate and the argument referent explicitly; do not emit partial theta-role entries with only the role and predicate. If noteBindings describe a DP as an external argument, an object as an internal argument, or explicitly say that a head selects a DP, CP, VP, or another complement, try to return matching argumentStructure and selectionLedger entries when the Lite route has room. If you return selectionLedger, avoid selector-only entries; name both the selector and the selected phrase/category explicitly whenever you include that ledger, and avoid internal placeholders like VP1 or InflP_mat. ` +
    `Treat ledgers as typed summaries of facts that are already explicit in growthFrames, not as an independent second analysis. Do not use a ledger to introduce a syntactic fact that is not already encoded in the derivation. If a noteBinding makes a structured claim, that same claim must already be supported by growthFrames and, when you include a dedicated ledger for it, by the matching ledger entry as well. Use subtype labels for control/raising/ECM when the note commits to a specific subtype. ` +
    `Do not let noteBindings or ledgers outrun the derivation. If a note would mention case, theta roles, selector/selectee relations, agreement, control, binding, locality, predication, or linearization but the matching fact is not encoded in growthFrames, simplify the note instead of asserting unsupported detail. ` +
    `Movement does not cancel ordinary predicate-argument bookkeeping. If an XP moves, still try to return the same caseAssignments, argumentStructure, and selectionLedger entries that would hold of its base-generated role and selector relation rather than dropping them just because the clause is a wh-question, topicalization, or another fronting configuration. ` +
    `If you return caseAssignments, identify the assignee explicitly with nodeId or assigneeLabel whenever the derivation makes that obvious. If you return argumentStructure, identify the referent and predicate explicitly rather than leaving them implicit. ` +
    `If noteBindings or the architecture note commit to control, raising, or ECM, clausalDependencies must include the matching type and the most specific compatible subtype rather than leaving subtype as a generic placeholder like "control" or "raising". ` +
    `Do not use generic wrap-up boilerplate such as "the derivation converges", "the overt word order is successfully derived", "the surface constituent order is derived", "the analysis successfully captures", or "this demonstrates how" followed by generic filler. If a closure sentence adds no concrete structural content, omit it. Prefer omitting closure entirely unless it contributes a new concrete payoff not already stated. Spend the Lite route's budget on getting the derivation and its notes right rather than on decorative extra sentences. ` +
    `Prefer direct structural closure wording over self-evaluative phrasing: say what the derivation establishes, not that it "successfully captures" or "demonstrates" something in general. ` +
    `A good closure sentence should name a real structural payoff already encoded in Growth, such as locality, a case/theta asymmetry, or a committed dependency contrast. If you cannot name a concrete payoff like that, do not return a closure binding. Phrase closure sentences as direct structural claims, not as self-referential sentences beginning with "This derivation" or "The analysis". Do not use closure merely to repeat movement, head-movement, or architecture facts that are already explicit in earlier note bindings. ` +
    `Every note binding must be a complete sentence, compact but elegant, with explicit structural wording rather than generic fallback prose. The Notes should sound like concise research notes, not robotic diagnostics. ` +
    `Every chain note must use chainId. Every chain note in noteBindings must include "chainId" and at least one structural anchor such as "stepIds" or "nodeIds", and every other note binding must still describe only structure and dependencies that are encoded in growthFrames. ` +
    `If a noteBinding makes a typed claim about case, theta-role/argument structure, selection, binding, clausal dependency, agreement/probe, predicate class, null elements, diagnostics, parameters, information structure, operator scope, voice/valency, linearization, locality, or predication, attach the matching typed ids on that noteBinding. Do not rely on generic supportIds alone for typed claims. ` +
    `If movement is encoded, public "chains" are required on the Flash Lite route as well. Every chain note on the Flash Lite route must include chainId plus at least one of stepIds or nodeIds. ` +
    `Before returning, compare noteBindings against the encoded move-like frames and make sure no encoded chain is omitted from the Notes. ` +
    `FINAL CHECK: return one coherent JSON answer only. growthFrames must be the authoritative derivation, and the latest decisive Growth frame must be sufficient for Babel to derive the final Canopy. Count your growthFrames before returning: if the Lite answer still has only one underspecified frame despite real derivational structure, expand it. Also run a final note-support self-audit: if any note uses a typed theoretical label, confirm that the matching public ledger exists and is cited; otherwise simplify the note back down to the directly visible Growth fact.`
  );
};

export const buildSingleParseContentsPrompt = (
  sentence,
  framework = 'xbar',
  modelRoute = 'flash-lite'
) => {
  if (modelRoute === 'pro') {
    return buildProGrowthFirstContentsPrompt(sentence, framework);
  }
  return buildLiteGrowthFirstContentsPrompt(sentence, framework);
};

export const buildParseContentsPrompt = (
  sentence,
  framework = 'xbar',
  modelRoute = 'flash-lite'
) => {
  const basePrompt = buildSingleParseContentsPrompt(sentence, framework, modelRoute);
  if (modelRoute === 'pro') {
    return basePrompt;
  }
  const repeatedConsistencyCheck =
    `CONSISTENCY RECHECK: Before returning, read the same request again and verify that your final JSON already encodes one coherent analysis. ` +
    `The overt terminals of the latest committed Growth frame must spell exactly: ${tokenizeSentenceSurfaceOrder(sentence).join(' | ')}. ` +
    `growthFrames and noteBindings must reflect the same movement story and the same structural commitments. ` +
    `If movement occurs, growthFrames must show the dependency as derivational state, must keep the full lower overt phrase before movement, and must keep an explicit lower trace/copy after movement. ` +
    `If a thematic subject ultimately surfaces high, Growth must still show its lower VP/predicate-domain merge site before later A-movement unless the subject is explicitly expletive or otherwise non-thematic. ` +
    `If the latest committed Growth frame yields a CP root, the clause spine under it must still be C-projected rather than re-labeled as D/D' or another lexical projection. ` +
    `Return one final JSON answer only.`;
  return (
    `${basePrompt}\n\n` +
    `${repeatedConsistencyCheck}`
  );
};

export const NOTES_SECOND_PASS_MAX_OUTPUT_TOKENS = 8192;
export const NOTES_SECOND_PASS_TEMPERATURE = 0.2;

export const buildNotesSecondPassSystemInstruction = (framework = 'xbar') => (
  `${NOTES_RAW_JSON_ONLY_INSTRUCTION} ` +
  `You are writing Babel noteBindings only. The syntactic analysis is already frozen and committed. ` +
  `Do not choose a new analysis, do not revise syntax, and do not invent new movement, ledgers, ids, or structural commitments. ` +
  `Write compact scientific noteBindings that explain only the provided committed ${framework === 'xbar' ? 'X-Bar' : 'Minimalist'} analysis. ` +
  `If the frozen analysis includes researchTrace, treat it as the preserved first-pass decision journal and reuse it when explaining why the committed analysis was chosen. ` +
  `Use only ids that already exist in the frozen analysis JSON. Do not invent chainIds, stepIds, nodeIds, supportIds, or typed ledger ids. ` +
  `If a public chain exists, reuse its chainId. If no public chain exists, anchor movement notes with stepIds and/or nodeIds only and do not invent a new chainId. ` +
  `Architecture notes should describe clause architecture, selection, and headedness rather than movement. ` +
  `Chain notes should describe only movement that is already encoded in movementEvents/growthFrames. ` +
  `Licensing notes should describe only case, theta-role, agreement, control, raising, ECM, or similar licensing facts that are already encoded and supported by the frozen ledgers. ` +
  `Closure notes are optional and must not introduce any new technical claim. ` +
  `If a typed ledger is missing, simplify the note rather than mentioning that typed domain. ` +
  `Every noteBinding must carry anchors back into the frozen analysis through chainId, stepIds, nodeIds, supportIds, researchTraceIds, and matching typed ids when relevant. ` +
  `Do not output explanations outside noteBindings, and do not include boilerplate such as "standard processing applied".`
);
